/**
 * Break-glass recovery contract (TASK-027.47, Q-DP24 closure decisions 1 and 4; hardened in TASK-027.47-R1).
 * This is the ONLY path that can restore a system-administrator account when it is otherwise unreachable
 * (lost/locked out, and — since TASK-027.47 — no longer manageable by a peer system administrator either). It is
 * deliberately NOT an HTTP endpoint: it exists only as `break-glass-recovery.service.ts` (plain class, never
 * registered with Nest DI or a controller — see the static test) invoked by the standalone CLI entrypoint
 * `break-glass-recovery.entrypoint.ts`, mirroring `apps/api/src/migrate.ts`'s pattern of a script that requires
 * direct database and environment access.
 *
 * Configuration is env-only and off by default: if `BREAK_GLASS_RECOVERY_TOKEN` is unset, recovery is entirely
 * disabled — there is no default token and none is ever generated by this code. The token is compared with a
 * digest + `timingSafeEqual` (never a plain `===`) so a timing side-channel cannot shorten the search space.
 *
 * `TOKEN_EXPIRES_AT` is optional (ISO-8601): the operational runbook is to set it alongside the token when a
 * recovery is opened, so an unused break-glass window closes itself even if never consumed. Independently of
 * that, every configured token is single-use forever (TASK-027.47-R1): `break_glass_recovery_events.tokenHash`
 * is UNIQUE, so a successful recovery permanently consumes that token value — the operator must rotate
 * `BREAK_GLASS_RECOVERY_TOKEN` before the next incident. Every attempt — success or refusal — also counts
 * against the persisted, cross-process rate limit (`break_glass_attempts`), independent of token correctness.
 */
export const BREAK_GLASS_ENV = {
  TOKEN: 'BREAK_GLASS_RECOVERY_TOKEN',
  TARGET_EMAIL: 'BREAK_GLASS_TARGET_EMAIL',
  NEW_PASSWORD: 'BREAK_GLASS_NEW_PASSWORD',
  TOKEN_EXPIRES_AT: 'BREAK_GLASS_TOKEN_EXPIRES_AT',
  RATE_LIMIT_MAX_ATTEMPTS: 'BREAK_GLASS_RATE_LIMIT_MAX_ATTEMPTS',
  RATE_LIMIT_WINDOW_MS: 'BREAK_GLASS_RATE_LIMIT_WINDOW_MS',
} as const

export const BREAK_GLASS_ACTION_CODE = 'BREAK_GLASS_RECOVERY'

export const BREAK_GLASS_DEFAULT_RATE_LIMIT_MAX_ATTEMPTS = 5
export const BREAK_GLASS_DEFAULT_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000

export const BREAK_GLASS_REASON = {
  NOT_CONFIGURED: 'BREAK_GLASS_NOT_CONFIGURED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_ALREADY_USED: 'TOKEN_ALREADY_USED',
  RATE_LIMITED: 'RATE_LIMITED',
  ACTIVE_ADMIN_EXISTS: 'ACTIVE_ADMIN_EXISTS',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  TARGET_NOT_FOUND: 'TARGET_NOT_FOUND',
  TARGET_NOT_SYSTEM_ADMIN: 'TARGET_NOT_SYSTEM_ADMIN',
  ERROR: 'ERROR',
} as const
export type BreakGlassReason = (typeof BREAK_GLASS_REASON)[keyof typeof BREAK_GLASS_REASON]

/**
 * Coarse lifecycle status of a break-glass recovery attempt (TASK-027.47-R1). Distinct from `BreakGlassReason`
 * (a specific, auditable code): `status` is the state-machine value a caller or operator checks; several reasons
 * can map to the same status (e.g. `WEAK_PASSWORD` and `TARGET_NOT_FOUND` are both `INVALID`).
 * `AVAILABLE` is never returned by `recover()` itself — it is the implicit pre-state of a token that has not yet
 * been used, expired or rate-limited.
 */
export const BREAK_GLASS_STATUS = {
  AVAILABLE: 'AVAILABLE',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID: 'INVALID',
  BLOCKED: 'BLOCKED',
  FAILED: 'FAILED',
} as const
export type BreakGlassStatus = (typeof BREAK_GLASS_STATUS)[keyof typeof BREAK_GLASS_STATUS]

export interface BreakGlassOutcome {
  success: boolean
  /** Present on both success and refusal — correlates the CLI's own log line with the audit row, without ever
   * containing (or being derived from) the token, password or hash. */
  eventId: string
  status: BreakGlassStatus
  reason?: BreakGlassReason
}
