import { PlatformAuditService } from '../../audit/platform-audit.service'
import { buildMockDb, chain } from '../../db/test-helpers/drizzle-mock'
import { ReferenceScadaPort, type ScadaAuditEntry, type ScadaAuditResult, type ScadaReasonCode } from './test-helpers/reference-scada-port'
import { DEFAULT_ALLOWLIST, SCOPE_MOSB, TEST_LIMITS, mockDriver, request } from './test-helpers/scada-readonly-port.contract'

/**
 * TASK-027.58-R1 — SCADA audit contract TEST MATRIX.
 *
 * One row per outcome class. Every row asserts the same invariants (exactly one audit entry, only the
 * allowed fields, caller-visible reason code == audited reason code, no rows/SQL/params/identifiers/
 * driver text, correct tenant/actor/correlation) plus the row-specific result/reason/source/driver
 * expectations.
 *
 * ALIGNED WITH DEC-0015 (TASK-027.64 R1; the earlier assumptions were superseded by AI1 decisions):
 *  - limit breaches (rows, payload, columns, time range, concurrency) are DENIED with a limitReason; timeouts,
 *    driver errors and cancellation are FAILED (cancellation = SCADA_QUERY_FAILED + reasonCode CANCELLED, Q-W520);
 *  - the correlation id is generated by the port (no client-supplied value exists);
 *  - the audit write is FAIL-CLOSED: if it cannot be written the rows are not returned (a denial keeps its outcome);
 *  - entries carry actionCode, tenant + customer root, row/column counts, duration and limitReason; the catalog id
 *    (`entityId`) of an existing-but-out-of-scope source is recorded, an unknown one is recorded as null.
 */
type Row = {
  name: string
  overrides?: Record<string, unknown>
  arrange?: (h: ReturnType<typeof mockDriver>) => void
  abortAfterMs?: number
  expected: { result: ScadaAuditResult; reasonCode: ScadaReasonCode; catalogId: string | null; driverCalls: number; limitReason?: string }
}

const HANG = (_s: unknown, signal: AbortSignal) => new Promise<never>((_, reject) => signal.addEventListener('abort', () => reject(new Error('aborted')), { once: true }))

const MATRIX: Row[] = [
  { name: 'success (own source)', expected: { result: 'SUCCEEDED', reasonCode: 'OK', catalogId: 'src-a', driverCalls: 1 } },

  { name: 'denied: unknown source', overrides: { sourceKey: 'no-such-source' }, expected: { result: 'DENIED', reasonCode: 'SOURCE_NOT_ALLOWED', catalogId: null, driverCalls: 0 } },
  { name: 'denied: source of another tenant', overrides: { sourceKey: 'src-b' }, expected: { result: 'DENIED', reasonCode: 'TENANT_SCOPE_DENIED', catalogId: 'src-b', driverCalls: 0 } },
  { name: 'denied: unresolved mapping', overrides: { sourceKey: 'src-unresolved' }, expected: { result: 'DENIED', reasonCode: 'SOURCE_MAPPING_UNRESOLVED', catalogId: 'src-unresolved', driverCalls: 0 } },
  { name: 'denied: column outside allowlist', overrides: { columns: ['password'] }, expected: { result: 'DENIED', reasonCode: 'COLUMN_NOT_ALLOWED', catalogId: 'src-a', driverCalls: 0 } },
  { name: 'denied: filter outside allowlist', overrides: { filters: { deger_b: 1 } }, expected: { result: 'DENIED', reasonCode: 'FILTER_NOT_ALLOWED', catalogId: 'src-a', driverCalls: 0 } },
  { name: 'denied: raw SQL / forbidden request field', overrides: { sql: 'DROP TABLE x' }, expected: { result: 'DENIED', reasonCode: 'INVALID_REQUEST', catalogId: null, driverCalls: 0 } },
  { name: 'denied: too many columns', overrides: { columns: ['kayit_tarihi', 'kayit_saati', 'deger_a', 'deger_b'] }, expected: { result: 'DENIED', reasonCode: 'COLUMN_LIMIT_EXCEEDED', catalogId: 'src-a', driverCalls: 0, limitReason: 'COLUMN_LIMIT' } },
  { name: 'denied: invalid time range', overrides: { timeRange: { from: new Date('2026-01-02'), to: new Date('2026-01-01') } }, expected: { result: 'DENIED', reasonCode: 'TIME_RANGE_INVALID', catalogId: 'src-a', driverCalls: 0 } },
  { name: 'denied: time range above source maximum', overrides: { timeRange: { from: new Date('2026-01-01'), to: new Date('2027-01-01') } }, expected: { result: 'DENIED', reasonCode: 'TIME_RANGE_EXCEEDED', catalogId: 'src-a', driverCalls: 0, limitReason: 'TIME_RANGE_LIMIT' } },

  { name: 'failed: driver error', arrange: h => h.impl.mockRejectedValue(new Error('Server=placeholder;Password=placeholder')), expected: { result: 'FAILED', reasonCode: 'SOURCE_UNAVAILABLE', catalogId: 'src-a', driverCalls: 1 } },
  { name: 'failed: timeout', arrange: h => h.impl.mockImplementation(HANG), expected: { result: 'FAILED', reasonCode: 'TIMEOUT', catalogId: 'src-a', driverCalls: 1, limitReason: 'TIMEOUT' } },
  { name: 'failed: caller cancellation', arrange: h => h.impl.mockImplementation(HANG), abortAfterMs: 5, expected: { result: 'FAILED', reasonCode: 'CANCELLED', catalogId: 'src-a', driverCalls: 1 } },
  { name: 'failed: row limit exceeded', arrange: h => h.impl.mockResolvedValue({ rows: Array.from({ length: TEST_LIMITS.maxRows + 1 }, (_, i) => ({ n: i })) }), expected: { result: 'DENIED', reasonCode: 'ROW_LIMIT_EXCEEDED', catalogId: 'src-a', driverCalls: 1, limitReason: 'ROW_LIMIT' } },
  { name: 'failed: payload limit exceeded', arrange: h => h.impl.mockResolvedValue({ rows: [{ blob: 'x'.repeat(TEST_LIMITS.maxPayloadBytes + 1) }] }), expected: { result: 'DENIED', reasonCode: 'PAYLOAD_LIMIT_EXCEEDED', catalogId: 'src-a', driverCalls: 1, limitReason: 'PAYLOAD_LIMIT' } },
]

const ALLOWED_FIELDS = ['actionCode', 'actorId', 'catalogId', 'columnCount', 'correlationId', 'customerRootTenantId', 'durationMs', 'limitReason', 'reasonCode', 'result', 'rowCount', 'tenantId']
const ACTION_BY_RESULT = { SUCCEEDED: 'SCADA_QUERY_SUCCEEDED', DENIED: 'SCADA_QUERY_DENIED', FAILED: 'SCADA_QUERY_FAILED' } as const
const FORBIDDEN_FRAGMENTS = ['SELECT', 'DB_ONE', 'tbl_one', 'dbo', 'kayit_tarihi', 'deger_a', 'Password', 'placeholder', 'ROW-MARKER', 'DROP TABLE']

function harness(row: Row, limits = TEST_LIMITS) {
  const d = mockDriver([{ kayit_tarihi: 'ROW-MARKER', deger_a: 1 }])
  const entries: ScadaAuditEntry[] = []
  const port = new ReferenceScadaPort(DEFAULT_ALLOWLIST, limits, d.driver, e => void entries.push(e), () => 'srv-corr')
  row.arrange?.(d)
  return { port, entries, ...d }
}

describe('SCADA audit contract matrix (TASK-027.58-R1)', () => {
  it.each(MATRIX)('$name', async row => {
    const h = harness(row)
    const controller = new AbortController()
    const overrides = { ...row.overrides, ...(row.abortAfterMs ? { signal: controller.signal } : {}) }
    if (row.abortAfterMs) setTimeout(() => controller.abort(), row.abortAfterMs)

    const outcome = await h.port.read('actor-1', SCOPE_MOSB, request(overrides)).then(
      () => ({ ok: true as const }),
      (error: { reasonCode: string }) => ({ ok: false as const, reasonCode: error.reasonCode }),
    )

    // exactly one audit entry per request, with only the allowed fields
    expect(h.entries).toHaveLength(1)
    const entry = h.entries[0]!
    expect(Object.keys(entry).sort()).toEqual(ALLOWED_FIELDS)
    const { driverCalls, limitReason, ...auditExpected } = row.expected
    expect(entry).toMatchObject({ actionCode: ACTION_BY_RESULT[row.expected.result], actorId: 'actor-1', tenantId: 'tenant-mosb', customerRootTenantId: 'root-mip', correlationId: 'srv-corr', limitReason: limitReason ?? null, ...auditExpected })
    expect(typeof entry.durationMs).toBe('number')
    expect(entry.rowCount).toBe(row.expected.result === 'SUCCEEDED' ? 1 : null)

    // driver interaction matches the outcome class
    expect(h.impl).toHaveBeenCalledTimes(driverCalls)

    // caller-visible outcome is consistent with what was audited
    if (row.expected.result === 'SUCCEEDED') expect(outcome.ok).toBe(true)
    else expect(outcome).toEqual({ ok: false, reasonCode: row.expected.reasonCode })
    // Q-W520: cancellation is FAILED + CANCELLED (no separate SCADA_QUERY_CANCELLED action)

    // nothing sensitive reaches the audit entry
    const serialized = JSON.stringify(entry)
    for (const fragment of FORBIDDEN_FRAGMENTS) expect(serialized).not.toContain(fragment)
  })

  it('concurrency-limit rejection is audited as DENIED (limit breach) without a driver call', async () => {
    const h = harness({ name: 'x', expected: { result: 'DENIED', reasonCode: 'CONCURRENCY_LIMIT', catalogId: 'src-a', driverCalls: 2 } }, { ...TEST_LIMITS, maxConcurrent: 1, poolSize: 1 })
    const releases: Array<() => void> = []
    h.impl.mockImplementation(() => new Promise(resolve => releases.push(() => resolve({ rows: [{ n: 1 }] }))))
    const first = h.port.read('actor-1', SCOPE_MOSB, request())
    await expect(h.port.read('actor-1', SCOPE_MOSB, request())).rejects.toMatchObject({ reasonCode: 'CONCURRENCY_LIMIT' })
    releases.forEach(release => release())
    await first
    expect(h.impl).toHaveBeenCalledTimes(1)
    expect(h.entries.map(e => [e.result, e.reasonCode, e.limitReason])).toEqual([
      ['DENIED', 'CONCURRENCY_LIMIT', 'CONCURRENCY_LIMIT'],
      ['SUCCEEDED', 'OK', null],
    ])
  })

  it('every outcome class in the matrix is covered: success, at least one denial and at least one failure', () => {
    const classes = new Set(MATRIX.map(row => row.expected.result))
    expect(classes).toEqual(new Set(['SUCCEEDED', 'DENIED', 'FAILED']))
  })

  it('an audit-write outage FAILS CLOSED for a success (no rows returned) and never masks a denial (DEC-0015 Q-SA05)', async () => {
    const d = mockDriver()
    const port = new ReferenceScadaPort(DEFAULT_ALLOWLIST, TEST_LIMITS, d.driver, () => Promise.reject(new Error('audit down')), () => 'srv-corr')
    await expect(port.read('actor-1', SCOPE_MOSB, request())).rejects.toMatchObject({ reasonCode: 'AUDIT_FAILED' })
    await expect(port.read('actor-1', SCOPE_MOSB, request({ sourceKey: 'src-b' }))).rejects.toMatchObject({ reasonCode: 'TENANT_SCOPE_DENIED' })
  })

  it('through the real PlatformAuditService each matrix outcome persists exactly one row whose metadata keys are the allowed set (tenant scope lives in metadata: the table has no tenant column)', async () => {
    const db = buildMockDb()
    db.select.mockReturnValue(chain([]))
    const service = new PlatformAuditService(db as never)
    const d = mockDriver()
    const port = new ReferenceScadaPort(DEFAULT_ALLOWLIST, TEST_LIMITS, d.driver, entry =>
      service.log({
        actorId: entry.actorId,
        actionCode: entry.actionCode,
        entityType: 'ScadaAnalysisQuery',
        entityId: entry.catalogId,
        summary: 'SCADA analysis query',
        metadata: { tenantId: entry.tenantId, customerRootTenantId: entry.customerRootTenantId, result: entry.result, reasonCode: entry.reasonCode, rowCount: entry.rowCount, columnCount: entry.columnCount, durationMs: entry.durationMs, limitReason: entry.limitReason, correlationId: entry.correlationId },
      }),
      () => 'srv-corr',
    )
    await port.read('actor-1', SCOPE_MOSB, request())
    await port.read('actor-1', SCOPE_MOSB, request({ sourceKey: 'src-b' })).catch(() => undefined)
    d.impl.mockRejectedValueOnce(new Error('x'))
    await port.read('actor-1', SCOPE_MOSB, request()).catch(() => undefined)
    expect(db.execute).toHaveBeenCalledTimes(3)
    const metadataRows = db.execute.mock.calls.map(call => {
      const chunks = (call[0] as { queryChunks: unknown[] }).queryChunks.filter(c => typeof c === 'string') as string[]
      return JSON.parse(chunks.find(c => c.startsWith('{"tenantId"')) ?? '{}') as Record<string, unknown>
    })
    for (const metadata of metadataRows) expect(Object.keys(metadata).sort()).toEqual(['columnCount', 'correlationId', 'customerRootTenantId', 'durationMs', 'limitReason', 'reasonCode', 'result', 'rowCount', 'tenantId'])
    expect(metadataRows.map(m => m['result'])).toEqual(['SUCCEEDED', 'DENIED', 'FAILED'])
  })
})
